# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7G5lmiP5nvCl-tLEYFzJd-T_aeyx0EX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#configuration de l'affichage
plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 12

data = {
    'Type_energie':['Conbustibles solides', 'Produits petroles', 'Gaz', 'Electricite'],
    'Pays_A':[20, 52, 33, 45],
    'Pays_B':[32, 114, 86, 18]
}
df = pd.DataFrame(data)
df.loc['Total'] = ['TOTAL', df['Pays_A'].sum(), df['Pays_B'].sum()]

print("-"*60)
print("Donnees des Exportations d'energie en MTEP")
print("-"*60)
print(df.to_string(index=False))
print(f"\nTotal General: {df['Pays_A'].sum() + df['Pays_B'].sum()} en Mtep")



df_pct = pd.DataFrame({
    'Type_energie': data['Type_energie'],
    'Pays_A_pct': (pd.Series(data['Pays_A']) / sum(data['Pays_A']) * 100).round(1),
    'Pays_B_pct': (pd.Series(data['Pays_B']) / sum(data['Pays_B']) * 100).round(1)
})
print("-"*60)
print("Structure en Pourcentage")
print("-"*60)
print(df_pct.to_string(index=False))

def diagramme_batons_simple(df):
  fig, ax = plt.subplots(figsize=(12, 7))
  x = np.arange(len(df.iloc[:-1]))
  width = 0.35
  bars1 = ax.bar(x - width/2, df['Pays_A'].iloc[:-1], width, label='Pays A', color='steelblue', edgecolor='black')
  bars2 = ax.bar(x + width/2, df['Pays_B'].iloc[:-1], width, label= 'Pays B', color='coral', edgecolor='black')

  ax.set_xlabel('Type d Energie', fontsize=12, fontweight='bold')
  ax.set_ylabel('Exportations en Mtep', fontsize=12, fontweight='bold')
  ax.set_title('Exportation de Pays A & Pays B', fontsize = 14, fontweight='bold')
  ax.set_xticks(x)
  ax.set_xticklabels(df['Type_energie'].iloc[:-1], rotation=45, ha='right')
  ax.legend()
  ax.grid(True, alpha=0.3, axis='y')

  for bars in [bars1, bars2]:
    for bar in bars:
      height = bar.get_height()
      ax.text(bar.get_x() + bar.get_width()/2, height + 1, f'{int(height)}', ha='center', va='bottom', fontsize=10)
  plt.tight_layout()
  plt.show()
  return fig
diagramme_batons_simple(df)

# ============================================================
# DIAGRAMME EN BÂTONS EMPILÉS
# ============================================================

def diagramme_batons_empiles(df):
    """
    Diagramme en bâtons empilés montrant la contribution de chaque type
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

    # Préparation des données
    types = df['Type_energie'].iloc[:-1]
    A = df['Pays_A'].iloc[:-1].values
    B = df['Pays_B'].iloc[:-1].values

    # Graphique 1 : Valeurs absolues empilées
    ax1.bar(types, A, label='Pays A', color='steelblue', edgecolor='black')
    ax1.bar(types, B, bottom=A, label='Pays B', color='coral', edgecolor='black')
    ax1.set_ylabel('Exportations totales (Mtep)', fontsize=12)
    ax1.set_title('Exportations totales par type', fontsize=12, fontweight='bold')
    ax1.legend()
    ax1.grid(True, alpha=0.3, axis='y')
    ax1.tick_params(axis='x', rotation=45)

    # Graphique 2 : Pourcentages
    total_A = A.sum()
    total_B = B.sum()

    pct_A = (A / total_A * 100).round(1)
    pct_B = (B / total_B * 100).round(1)

    x2 = np.arange(len(types))
    width = 0.35

    ax2.bar(x2 - width/2, pct_A, width, label='Pays A',
            color='steelblue', edgecolor='black')
    ax2.bar(x2 + width/2, pct_B, width, label='Pays B',
            color='coral', edgecolor='black')
    ax2.set_ylabel('Pourcentage (%)', fontsize=12)
    ax2.set_title('Structure en pourcentage', fontsize=12, fontweight='bold')
    ax2.set_xticks(x2)
    ax2.set_xticklabels(types, rotation=45, ha='right')
    ax2.legend()
    ax2.grid(True, alpha=0.3, axis='y')

    plt.suptitle('Comparaison Pays A vs Pays B', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()

diagramme_batons_empiles(df)

# ============================================================
# GRAPHIQUES CIRCULAIRES (PIE CHARTS)
# ============================================================

def graphiques_circulaires(df, df_pct):
    """
    Crée deux camemberts comparatifs avec les pourcentages
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    # Couleurs personnalisées
    colors = ['#ff9999', '#66b3ff', '#99ff99', '#ffcc99']

    # Camembert Pays A
    wedges1, texts1, autotexts1 = ax1.pie(
        df['Pays_A'].iloc[:-1],
        labels=df['Type_energie'].iloc[:-1],
        autopct='%1.1f%%',
        colors=colors,
        startangle=90,
        explode=[0.05] * 4,  # légère séparation
        shadow=True
    )
    ax1.set_title(f'Pays A - Total: {df["Pays_A"].iloc[-1]} Mtep',
                  fontsize=12, fontweight='bold')

    # Camembert Pays B
    wedges2, texts2, autotexts2 = ax2.pie(
        df['Pays_B'].iloc[:-1],
        labels=df['Type_energie'].iloc[:-1],
        autopct='%1.1f%%',
        colors=colors,
        startangle=90,
        explode=[0.05] * 4,
        shadow=True
    )
    ax2.set_title(f'Pays B - Total: {df["Pays_B"].iloc[-1]} Mtep',
                  fontsize=12, fontweight='bold')

    plt.suptitle('Structure des exportations d\'énergie',
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()

graphiques_circulaires(df, df_pct)

# ============================================================
# VERSION AVANCÉE AVEC TABLEAU DE BORD
# ============================================================

def tableau_bord_exportations(df):
    """
    Crée un tableau de bord complet avec plusieurs visualisations
    """
    fig = plt.figure(figsize=(16, 10))

    # 1. Diagramme en bâtons comparatif (en haut à gauche)
    ax1 = plt.subplot(2, 3, 1)
    x = np.arange(4)
    width = 0.35
    ax1.bar(x - width/2, df['Pays_A'].iloc[:-1], width,
            color='steelblue', edgecolor='black', label='Pays A')
    ax1.bar(x + width/2, df['Pays_B'].iloc[:-1], width,
            color='coral', edgecolor='black', label='Pays B')
    ax1.set_xticks(x)
    ax1.set_xticklabels(df['Type_energie'].iloc[:-1], rotation=45, ha='right')
    ax1.set_ylabel('Mtep')
    ax1.set_title('Volumes absolus')
    ax1.legend()
    ax1.grid(True, alpha=0.3, axis='y')

    # 2. Camembert Pays A (en haut au milieu)
    ax2 = plt.subplot(2, 3, 2)
    colors = plt.cm.Set3(np.linspace(0, 1, 4))
    wedges, texts, autotexts = ax2.pie(
        df['Pays_A'].iloc[:-1],
        autopct='%1.1f%%',
        colors=colors,
        startangle=90
    )
    ax2.set_title(f'Pays A ({df["Pays_A"].iloc[-1]} Mtep)')

    # 3. Camembert Pays B (en haut à droite)
    ax3 = plt.subplot(2, 3, 3)
    wedges, texts, autotexts = ax3.pie(
        df['Pays_B'].iloc[:-1],
        autopct='%1.1f%%',
        colors=colors,
        startangle=90
    )
    ax3.set_title(f'Pays B ({df["Pays_B"].iloc[-1]} Mtep)')

    # 4. Diagramme en barres des parts (en bas à gauche)
    ax4 = plt.subplot(2, 3, 4)
    pct_A = df['Pays_A'].iloc[:-1] / df['Pays_A'].iloc[-1] * 100
    pct_B = df['Pays_B'].iloc[:-1] / df['Pays_B'].iloc[-1] * 100

    ax4.bar(x - width/2, pct_A, width, color='steelblue', edgecolor='black')
    ax4.bar(x + width/2, pct_B, width, color='coral', edgecolor='black')
    ax4.set_xticks(x)
    ax4.set_xticklabels(df['Type_energie'].iloc[:-1], rotation=45, ha='right')
    ax4.set_ylabel('Pourcentage (%)')
    ax4.set_title('Parts relatives')
    ax4.grid(True, alpha=0.3, axis='y')

    # 5. Diagramme en cascade (waterfall) - en bas à droite
    ax5 = plt.subplot(2, 3, (5, 6))

    # Calcul des différences
    diff = df['Pays_B'].iloc[:-1].values - df['Pays_A'].iloc[:-1].values
    types = df['Type_energie'].iloc[:-1]
    colors_diff = ['red' if d < 0 else 'green' for d in diff]

    ax5.bar(types, diff, color=colors_diff, edgecolor='black', alpha=0.7)
    ax5.axhline(y=0, color='black', linewidth=1)
    ax5.set_ylabel('Différence B - A (Mtep)')
    ax5.set_title('Écarts entre Pays B et Pays A')
    ax5.grid(True, alpha=0.3, axis='y')
    ax5.tick_params(axis='x', rotation=45)

    plt.suptitle('ANALYSE COMPARATIVE DES EXPORTATIONS D\'ÉNERGIE',
                 fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

tableau_bord_exportations(df)

# ============================================================
# STATISTIQUES DESCRIPTIVES
# ============================================================

def analyse_statistique(df):
    """
    Calcule les principales statistiques pour chaque pays
    """
    print("=" * 70)
    print("ANALYSE STATISTIQUE DES EXPORTATIONS")
    print("=" * 70)

    for pays in ['Pays_A', 'Pays_B']:
        valeurs = df[pays].iloc[:-1].values
        total = df[pays].iloc[-1]

        print(f"\n--- {pays.replace('_', ' ')} ---")
        print(f"Total exportations : {total} Mtep")
        print(f"Moyenne par type : {valeurs.mean():.1f} Mtep")
        print(f"Écart-type : {valeurs.std():.1f} Mtep")
        print(f"Minimum : {valeurs.min()} Mtep ({df['Type_energie'].iloc[valeurs.argmin()]})")
        print(f"Maximum : {valeurs.max()} Mtep ({df['Type_energie'].iloc[valeurs.argmax()]})")
        print(f"Étendue : {valeurs.max() - valeurs.min()} Mtep")

        # Coefficient de variation (dispersion relative)
        cv = (valeurs.std() / valeurs.mean()) * 100
        print(f"Coefficient de variation : {cv:.1f}%")

        # Indice de concentration de Hirschman-Herfindahl
        parts = (valeurs / total * 100) / 100  # proportions
        hhi = (parts ** 2).sum() * 10000
        print(f"Indice HHI (concentration) : {hhi:.0f}")
        if hhi < 1500:
            print("  → Structure diversifiée")
        elif hhi < 2500:
            print("  → Concentration modérée")
        else:
            print("  → Forte concentration")

    # Comparaison des structures
    print("\n" + "-" * 40)
    print("COMPARAISON DES STRUCTURES")
    print("-" * 40)

    # Test du χ² d'indépendance (pour voir si les structures diffèrent)
    from scipy.stats import chi2_contingency

    tableau_contingence = np.array([
        df['Pays_A'].iloc[:-1].values,
        df['Pays_B'].iloc[:-1].values
    ])

    chi2, p_value, dof, expected = chi2_contingency(tableau_contingence)

    print(f"Test du χ² d'indépendance :")
    print(f"  χ² = {chi2:.2f}")
    print(f"  ddl = {dof}")
    print(f"  p-value = {p_value:.4f}")

    if p_value < 0.05:
        print("  → Les structures sont significativement différentes")
    else:
        print("  → Pas de différence significative détectée")

    return chi2, p_value

# Exécution
chi2, p_value = analyse_statistique(df)

# ============================================================
# BOXPLOTS ET DISTRIBUTIONS
# ============================================================

def visualiser_distributions(df):
    """
    Crée des boxplots pour comparer les distributions
    """
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Préparation des données
    data_A = df['Pays_A'].iloc[:-1].values
    data_B = df['Pays_B'].iloc[:-1].values

    # Boxplot
    axes[0].boxplot([data_A, data_B], labels=['Pays A', 'Pays B'],
                    patch_artist=True,
                    boxprops=dict(facecolor='lightblue'),
                    medianprops=dict(color='red', linewidth=2))
    axes[0].set_ylabel('Exportations (Mtep)')
    axes[0].set_title('Boxplot des exportations par type')
    axes[0].grid(True, alpha=0.3, axis='y')

    # Histogrammes superposés
    axes[1].hist(data_A, bins=4, alpha=0.7, label='Pays A',
                 color='steelblue', edgecolor='black')
    axes[1].hist(data_B, bins=4, alpha=0.7, label='Pays B',
                 color='coral', edgecolor='black')
    axes[1].set_xlabel('Exportations (Mtep)')
    axes[1].set_ylabel('Fréquence')
    axes[1].set_title('Distribution des exportations')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3, axis='y')

    plt.suptitle('Analyse des distributions', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.show()

visualiser_distributions(df)

def rapport_analyse(df):
    """
    Génère un rapport complet d'analyse
    """
    print("\n" + "=" * 70)
    print("RAPPORT D'ANALYSE - EXPORTATIONS D'ÉNERGIE")
    print("=" * 70)

    # 1. Volume total
    total_A = df['Pays_A'].iloc[-1]
    total_B = df['Pays_B'].iloc[-1]
    print(f"\n1. VOLUME TOTAL")
    print(f"   Pays A : {total_A} Mtep")
    print(f"   Pays B : {total_B} Mtep")
    print(f"   Rapport B/A : {total_B/total_A:.2f}")

    # 2. Structure
    print(f"\n2. STRUCTURE (en %)")
    for idx, row in df_pct.iterrows():
        print(f"   {row['Type_energie']}:")
        print(f"     Pays A: {row['Pays_A_pct']}%")
        print(f"     Pays B: {row['Pays_B_pct']}%")

    # 3. Points clés
    print(f"\n3. POINTS CLÉS")

    # Énergie dominante
    dom_A = df.loc[df['Pays_A'].iloc[:-1].idxmax(), 'Type_energie']
    dom_B = df.loc[df['Pays_B'].iloc[:-1].idxmax(), 'Type_energie']
    print(f"   Énergie principale :")
    print(f"     Pays A : {dom_A}")
    print(f"     Pays B : {dom_B}")

    # Spécialisation
    print(f"\n   Spécialisation :")
    if dom_A == 'Electricité' and dom_B == 'Produits pétroliers':
        print("     Pays A spécialisé dans l'électricité (hydraulique/nucléaire?)")
        print("     Pays B spécialisé dans les produits pétroliers")

    # 4. Recommandations
    print(f"\n4. RECOMMANDATIONS POUR ANALYSE APPROFONDIE")
    print("   • Étudier les raisons de la dominance pétrolière au Pays B")
    print("   • Analyser le potentiel de développement des énergies renouvelables")
    print("   • Comparer avec la consommation intérieure")
    print("   • Étudier l'évolution temporelle")

rapport_analyse(df)