# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7G5lmiP5nvCl-tLEYFzJd-T_aeyx0EX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

plt.style.use('default')
sns.set_palette('husl')
plt.rcParams['figure.figsize'] = (14, 8)
plt.rcParams['font.size'] = 12

data = {
    'borne_inf' : [0,1,2,3,5,10,20],
    'borne_sup' : [1,2,3,5,10,20,40],
    'effectif' : [26, 35, 29, 53, 105, 71, 25]
}
df = pd.DataFrame(data)

df['centre'] = (df['borne_inf'] + df['borne_sup']) / 2
df['amplitude'] = df['borne_sup'] - df['borne_inf']
df['densite'] = df['effectif'] / df['amplitude']
df['freq_rel'] = df['effectif'] / df['effectif'].sum() * 100

print("-"*60)
print("Donnes des Exploitations laitieres")
print("-" *60)
print(df.to_string(index=False))
print(f"Nombre total des exploitation: {df['effectif'].sum()}")

#tracé Histogramme
def tracer_histogramme(df):
  fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
  ax1.bar(df['centre'], df['effectif'],
      width = df['amplitude'] * 0.9,
      edgecolor= 'black'       ,
      color= 'steelblue',
      alpha=0.7
  )
  ax1.set_xlabel('Production', fontsize=12)
  ax1.set_ylabel('Nombre d exploitation', fontsize=12)
  ax1.set_title('Histogramme effectifs bruts', fontsize=14, fontweight='bold')
  ax1.grid(True, alpha=0.3, axis='y')

  largeurs = df['amplitude'].values
  hauteurs = df['densite'].values

  ax2.bar(df['centre'], hauteurs, width=largeurs * 0.9, edgecolor='black', color='coral', alpha=0.7 )

  ax2.set_xlabel('Production', fontsize=12)
  ax2.set_ylabel('Densite', fontsize=12)
  ax2.set_title('Histogramme densite correcte ', fontsize=14, fontweight='bold')
  ax2.grid(True, alpha=0.3, axis='y')

  plt.suptitle('Distribution des exploitations selon la production', fontsize=16, fontweight='bold')
  plt.tight_layout()
  plt.show()
  return

tracer_histogramme(df)

#classe Modale
def determiner_classe_modale(df):
  idx_modale = df['densite'].idxmax()
  classe_modale = df.loc[idx_modale]
  print("-"*60)
  print("Classe Modale")
  print("-" *60)
  print(f"Classe : [{classe_modale['borne_inf']}; {classe_modale['borne_sup']}[")
  print(f"Effectif : {classe_modale['effectif']} exploitations")
  print(f"Amplitude : {classe_modale['amplitude']}")
  print(f"Densité : {classe_modale['densite']:.2f} expl./unité")

  idx_max_effectif = df['effectif'].idxmax()
  if idx_modale != idx_max_effectif:
    print(f"Classe avec plus grand effectif : [{df.loc[idx_max_effectif, 'borne_inf']}; "
              f"{df.loc[idx_max_effectif, 'borne_sup']}[ (effectif = {df.loc[idx_max_effectif, 'effectif']})")


  return classe_modale
classe_modale = determiner_classe_modale(df)

# ============================================================
# VISUALISATION AVEC MISE EN ÉVIDENCE DE LA CLASSE MODALE
# ============================================================

def visualiser_classe_modale(df, classe_modale):
    """
    Histogramme avec la classe modale mise en évidence
    """
    plt.figure(figsize=(12, 6))

    # Couleurs : une couleur différente pour la classe modale
    colors = ['lightgray'] * len(df)
    colors[df['densite'].idxmax()] = 'coral'

    plt.bar(df['centre'], df['densite'],
            width=df['amplitude'] * 0.9,
            color=colors,
            edgecolor='black',
            alpha=0.7)

    # Annotation de la classe modale
    idx_mod = df['densite'].idxmax()
    plt.annotate(f'Classe modale\n[{df.loc[idx_mod, "borne_inf"]}; {df.loc[idx_mod, "borne_sup"]}[\n'
                f'Densité = {df.loc[idx_mod, "densite"]:.2f}',
                xy=(df.loc[idx_mod, 'centre'], df.loc[idx_mod, 'densite']),
                xytext=(df.loc[idx_mod, 'centre'] + 5, df.loc[idx_mod, 'densite'] + 2),
                arrowprops=dict(arrowstyle='->', color='red', lw=2),
                fontsize=11,
                bbox=dict(boxstyle="round,pad=0.3", facecolor="yellow", alpha=0.7))

    plt.xlabel('Production (milliers de litres)', fontsize=12)
    plt.ylabel('Densité', fontsize=12)
    plt.title('Histogramme avec mise en évidence de la classe modale',
              fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3, axis='y')
    plt.tight_layout()
    plt.show()

visualiser_classe_modale(df, classe_modale)

# ============================================================
# FRÉQUENCES CUMULÉES
# ============================================================

# Calcul des effectifs cumulés
df['effectif_cum'] = df['effectif'].cumsum()
df['freq_cum'] = df['effectif_cum'] / df['effectif'].sum() * 100

# Pour la courbe, on prend les bornes supérieures
df_cum = pd.DataFrame({
    'borne_sup': df['borne_sup'],
    'freq_cum': df['freq_cum']
})

# Ajout du point (0,0) pour commencer la courbe
df_cum = pd.concat([
    pd.DataFrame({'borne_sup': [0], 'freq_cum': [0]}),
    df_cum
], ignore_index=True)

print("=" * 60)
print("TABLEAU DES FRÉQUENCES CUMULÉES")
print("=" * 60)
print(df[['borne_inf', 'borne_sup', 'effectif', 'effectif_cum', 'freq_cum']].to_string(index=False))

# ============================================================
# COURBE DES FRÉQUENCES CUMULÉES
# ============================================================

def tracer_courbe_freq_cumulees(df_cum, df):
    """
    Trace la courbe des fréquences cumulées (polygone des fréquences)
    """
    plt.figure(figsize=(12, 7))

    # Courbe en escalier (plus fidèle pour des classes)
    plt.step(df_cum['borne_sup'], df_cum['freq_cum'],
             where='post', linewidth=3, color='steelblue',
             label='Fréquences cumulées')

    # Points de jonction
    plt.scatter(df_cum['borne_sup'], df_cum['freq_cum'],
                color='red', s=100, zorder=5, edgecolor='black')

    # Lignes horizontales pour la médiane et les quartiles
    plt.axhline(y=25, color='gray', linestyle='--', alpha=0.5, label='Q1 (25%)')
    plt.axhline(y=50, color='green', linestyle='--', alpha=0.7, linewidth=2, label='Médiane (50%)')
    plt.axhline(y=75, color='gray', linestyle='--', alpha=0.5, label='Q3 (75%)')

    plt.xlabel('Production (milliers de litres)', fontsize=12)
    plt.ylabel('Fréquences cumulées (%)', fontsize=12)
    plt.title('Courbe des fréquences cumulées', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.xlim(-1, 42)
    plt.ylim(0, 105)

    # Annotation des points clés
    plt.text(30, 52, 'Médiane', fontsize=11, color='green', fontweight='bold')

    plt.tight_layout()
    plt.show()

tracer_courbe_freq_cumulees(df_cum, df)

# ============================================================
# MOYENNE (approchée par les centres de classes)
# ============================================================

def calculer_moyenne(df):
    """
    Calcule la moyenne approchée à partir des centres de classes
    """
    total_exploitations = df['effectif'].sum()
    somme_produits = (df['centre'] * df['effectif']).sum()
    moyenne = somme_produits / total_exploitations

    print("=" * 60)
    print("MOYENNE APPROCHÉE")
    print("=" * 60)
    print(f"Moyenne = {moyenne:.2f} milliers de litres")
    print(f"          soit {moyenne*1000:.0f} litres")

    return moyenne

moyenne = calculer_moyenne(df)

# ============================================================
# MÉDIANE (par interpolation linéaire)
# ============================================================

def calculer_mediane(df):
    """
    Calcule la médiane par interpolation linéaire dans la classe médiane
    """
    total = df['effectif'].sum()
    rang_mediane = total / 2  # 172e exploitation

    # Recherche de la classe médiane
    effectif_cum = 0
    for idx, row in df.iterrows():
        if effectif_cum + row['effectif'] >= rang_mediane:
            classe_mediane = row
            effectif_avant = effectif_cum
            break
        effectif_cum += row['effectif']

    # Interpolation linéaire
    # Med = borne_inf + (rang_mediane - effectif_avant) / effectif_classe * amplitude
    mediane = (classe_mediane['borne_inf'] +
               (rang_mediane - effectif_avant) / classe_mediane['effectif'] *
               classe_mediane['amplitude'])

    print("=" * 60)
    print("MÉDIANE")
    print("=" * 60)
    print(f"Rang de la médiane : {rang_mediane:.0f}e exploitation")
    print(f"Classe médiane : [{classe_mediane['borne_inf']}; {classe_mediane['borne_sup']}[")
    print(f"Effectif avant la classe : {effectif_avant}")
    print(f"Effectif de la classe : {classe_mediane['effectif']}")
    print(f"Médiane = {mediane:.2f} milliers de litres")
    print(f"          soit {mediane*1000:.0f} litres")

    return mediane, classe_mediane

mediane, classe_mediane = calculer_mediane(df)

# ============================================================
# QUARTILES ET ÉCART INTERQUARTILE
# ============================================================

def calculer_quartiles(df):
    """
    Calcule Q1, Q3 et l'écart interquartile
    """
    total = df['effectif'].sum()

    # Q1 : rang = total/4
    rang_q1 = total / 4

    # Q3 : rang = 3*total/4
    rang_q3 = 3 * total / 4

    # Recherche des classes
    def trouver_valeur_quantile(rang):
        effectif_cum = 0
        for idx, row in df.iterrows():
            if effectif_cum + row['effectif'] >= rang:
                quantile = (row['borne_inf'] +
                           (rang - effectif_cum) / row['effectif'] *
                           row['amplitude'])
                return quantile, row, effectif_cum
            effectif_cum += row['effectif']

    q1, classe_q1, avant_q1 = trouver_valeur_quantile(rang_q1)
    q3, classe_q3, avant_q3 = trouver_valeur_quantile(rang_q3)

    ecart_interquartile = q3 - q1

    print("=" * 60)
    print("QUARTILES")
    print("=" * 60)
    print(f"Q1 (25%) : {q1:.2f} milliers de litres")
    print(f"   Rang : {rang_q1:.0f}e exploitation")
    print(f"   Classe : [{classe_q1['borne_inf']}; {classe_q1['borne_sup']}[")
    print(f"\nQ3 (75%) : {q3:.2f} milliers de litres")
    print(f"   Rang : {rang_q3:.0f}e exploitation")
    print(f"   Classe : [{classe_q3['borne_inf']}; {classe_q3['borne_sup']}[")
    print(f"\nÉcart interquartile : {ecart_interquartile:.2f} milliers de litres")
    print(f"                     soit {ecart_interquartile*1000:.0f} litres")

    return q1, q3, ecart_interquartile

q1, q3, eiq = calculer_quartiles(df)

# ============================================================
# VARIANCE ET ÉCART-TYPE
# ============================================================

def calculer_variance(df, moyenne):
    """
    Calcule la variance et l'écart-type (formule pondérée)
    """
    total = df['effectif'].sum()

    # Somme des (centre - moyenne)² * effectif
    somme_carres_ecarts = ((df['centre'] - moyenne)**2 * df['effectif']).sum()

    # Variance (population, pas échantillon)
    variance = somme_carres_ecarts / total

    # Écart-type
    ecart_type = np.sqrt(variance)

    # Coefficient de variation
    cv = (ecart_type / moyenne) * 100

    print("=" * 60)
    print("VARIANCE ET ÉCART-TYPE")
    print("=" * 60)
    print(f"Variance : {variance:.2f} (milliers de litres)²")
    print(f"Écart-type : {ecart_type:.2f} milliers de litres")
    print(f"            soit {ecart_type*1000:.0f} litres")
    print(f"Coefficient de variation : {cv:.1f}%")

    if cv < 15:
        print("→ Distribution peu dispersée (homogène)")
    elif cv < 30:
        print("→ Dispersion modérée")
    else:
        print("→ Distribution très dispersée (hétérogène)")

    return variance, ecart_type

variance, ecart_type = calculer_variance(df, moyenne)

# ============================================================
# TABLEAU DE BORD COMPLET
# ============================================================

def tableau_bord_complet(df, moyenne, mediane, q1, q3, variance, ecart_type):
    """
    Crée un tableau de bord avec toutes les informations
    """
    fig = plt.figure(figsize=(16, 10))

    # 1. Histogramme des densités
    ax1 = plt.subplot(2, 3, 1)
    ax1.bar(df['centre'], df['densite'],
            width=df['amplitude'] * 0.9,
            color='steelblue', edgecolor='black', alpha=0.7)
    ax1.set_xlabel('Production')
    ax1.set_ylabel('Densité')
    ax1.set_title('Histogramme (densités)')
    ax1.grid(True, alpha=0.3, axis='y')

    # 2. Boîte à moustaches (boxplot)
    ax2 = plt.subplot(2, 3, 2)
    # Simulation des données pour le boxplot
    np.random.seed(42)
    simulated_data = []
    for _, row in df.iterrows():
        simulated_data.extend(np.random.uniform(
            row['borne_inf'], row['borne_sup'],
            size=row['effectif']
        ))
    ax2.boxplot(simulated_data, vert=False)
    ax2.set_xlabel('Production')
    ax2.set_title('Boîte à moustaches')
    ax2.grid(True, alpha=0.3, axis='x')

    # 3. Courbe des fréquences cumulées
    ax3 = plt.subplot(2, 3, 3)
    ax3.step(df_cum['borne_sup'], df_cum['freq_cum'],
             where='post', linewidth=2, color='coral')
    ax3.axhline(y=50, color='green', linestyle='--', alpha=0.5)
    ax3.set_xlabel('Production')
    ax3.set_ylabel('Fréquences cumulées (%)')
    ax3.set_title('Courbe cumulative')
    ax3.grid(True, alpha=0.3)

    # 4. Tableau des indicateurs
    ax4 = plt.subplot(2, 3, (4, 6))
    ax4.axis('off')

    # Création d'un tableau avec les résultats
    cell_text = [
        ['Nombre d\'exploitations', f'{df["effectif"].sum()}'],
        ['Production totale', f'{moyenne * df["effectif"].sum():.0f} milliers L'],
        ['Production moyenne', f'{moyenne:.2f} milliers L'],
        ['Production médiane', f'{mediane:.2f} milliers L'],
        ['Q1 (25%)', f'{q1:.2f} milliers L'],
        ['Q3 (75%)', f'{q3:.2f} milliers L'],
        ['Écart interquartile', f'{eiq:.2f} milliers L'],
        ['Variance', f'{variance:.2f} (milliers L)²'],
        ['Écart-type', f'{ecart_type:.2f} milliers L'],
        ['Coefficient de variation', f'{(ecart_type/moyenne*100):.1f}%']
    ]

    table = ax4.table(cellText=cell_text,
                      colLabels=['Indicateur', 'Valeur'],
                      cellLoc='left',
                      loc='center',
                      colWidths=[0.4, 0.3])
    table.auto_set_font_size(False)
    table.set_fontsize(11)
    table.scale(1.2, 1.5)

    # Coloration des cellules
    for (i, j), cell in table.get_celld().items():
        if i == 0:  # En-tête
            cell.set_facecolor('#40466e')
            cell.set_text_props(color='white', weight='bold')
        elif i % 2 == 0:
            cell.set_facecolor('#f0f0f0')

    plt.suptitle('ANALYSE STATISTIQUE DES EXPLOITATIONS LAITIÈRES',
                 fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

tableau_bord_complet(df, moyenne, mediane, q1, q3, variance, ecart_type)

# ============================================================
# RAPPORT FINAL
# ============================================================

print("\n" + "=" * 70)
print("RAPPORT D'ANALYSE - EXPLOITATIONS LAITIÈRES")
print("=" * 70)

print(f"""
1. STRUCTURE DE LA DISTRIBUTION
   • {df['effectif'].sum()} exploitations analysées
   • Classe modale : [{classe_modale['borne_inf']}; {classe_modale['borne_sup']}[
     (densité la plus forte : {classe_modale['densite']:.2f} expl./unité)

2. TENDANCE CENTRALE
   • Production moyenne : {moyenne:.2f} milliers de litres
   • Production médiane : {mediane:.2f} milliers de litres
   • La {'moyenne' if moyenne > mediane else 'médiane'} est plus élevée,
     distribution {'asymétrique à droite' if moyenne > mediane else 'asymétrique à gauche'}

3. DISPERSION
   • Écart-type : {ecart_type:.2f} milliers de litres
   • Écart interquartile : {eiq:.2f} milliers de litres
   • 50% des exploitations produisent entre {q1:.2f} et {q3:.2f} milliers de litres

4. HOMOGÉNÉITÉ
   • Coefficient de variation : {(ecart_type/moyenne*100):.1f}%
   • La distribution est {'homogène' if (ecart_type/moyenne*100) < 30 else 'hétérogène'}

5. INTERPRÉTATION MÉTIER
   • La majorité des exploitations ({df.iloc[4:6]["effectif"].sum()} sur {df["effectif"].sum()})
     se concentre dans les classes 5-20 milliers de litres
   • Il existe un petit groupe d'exploitations très productives (20-40 milliers L)
   • Un autre groupe d'exploitations a une production très faible (moins de 2 milliers L)
""")