# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cGn2kGjA3L8tkKyrOKKdRB82V4bdF0AD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler



#données issues de cours https://maths.cnam.fr/IMG/pdf/1-Introduction_analyse_de_donnees-2013_cle8ba3a2.pdf
# Première table (caractéristiques principales)

df1 = pd.DataFrame({
    'NOM_COURT': ['ALFA 156', 'AUDIA3', 'AUDIA8', 'AVENSIS', 'BMW X5', 'BMW530',
                  'CHRYS300', 'CITRONC2', 'CITRONC4', 'CITRONC5', 'CLIO', 'CORSA',
                  'CORVETTE', 'FIESTA', 'GOLF', 'LAGUNA', 'LANDCRUI', 'MAZDARX8',
                  'MEGANECC', 'MERC_A'],
    'PUISSANCE': [250, 102, 280, 115, 218, 231, 340, 61, 138, 210, 100, 70,
                  404, 68, 75, 165, 204, 231, 165, 140],
    'CYLINDREE': [3179, 1595, 3697, 1995, 2993, 2979, 5654, 1124, 1997, 2496,
                  1461, 1248, 5970, 1399, 1968, 1998, 4164, 1308, 1998, 1991],
    'VITESSE': [250, 185, 250, 195, 210, 250, 250, 158, 207, 230, 185, 165,
                300, 164, 163, 218, 170, 235, 225, 201],
    'LONGUEUR': [443, 421, 506, 463, 467, 485, 502, 367, 426, 475, 382, 384,
                 444, 392, 421, 458, 489, 443, 436, 384],
    'LARGEUR': [175, 177, 203, 176, 188, 185, 188, 166, 178, 178, 164, 165,
                185, 168, 176, 178, 194, 177, 178, 177]
})

# Deuxième table
df2 = pd.DataFrame({
    'NOM_COURT': ['ALFA 156', 'AUDIA3', 'AUDIA8', 'AVENSIS', 'BMW X5', 'BMW530',
                  'CHRYS300', 'CITRONC2', 'CITRONC4', 'CITRONC5', 'CLIO', 'CORSA',
                  'CORVETTE', 'FIESTA', 'GOLF', 'LAGUNA', 'LANDCRUI', 'MAZDARX8',
                  'MEGANECC', 'MERC_A'],
    'HAUTEUR': [141, 143, 145, 148, 172, 147, 148, 147, 146, 148, 142, 144,
                125, 144, 149, 143, 185, 134, 141, 160],
    'POIDS': [1410, 1205, 1770, 1400, 2095, 1495, 1835, 932, 1381, 1589, 980,
              1035, 1517, 1138, 1217, 1320, 2495, 1390, 1415, 1340],
    'COFFRE': [378, 350, 500, 510, 465, 520, 442, 224, 314, 471, 255, 260,
               295, 261, 350, 430, 403, 287, 190, 435],
    'RESERVOIR': [63, 55, 90, 60, 93, 70, 72, 41, 60, 65, 50, 45,
                  69, 45, 55, 70, 96, 61, 60, 54],
    'CONSO': [12.1, 7, 11.7, 5.8, 8.6, 9.5, 12.2, 5.9, 5.4, 10, 4.3, 4.7,
              13, 4.4, 5.4, 8.2, 11.1, 11.4, 8, 5.4],
    'CO2': [287, 168, 281, 155, 229, 231, 291, 141, 142, 238, 113, 127,
            310, 117, 143, 196, 292, 284, 191, 141],
    'PRIX': [40800, 21630, 78340, 26400, 52000, 46400, 54900, 10700, 23400, 33000,
             17600, 13590, 63350, 14150, 19140, 25350, 67100, 34000, 27800, 24550]
})

# Même chose pour les 20 autres voitures
df3 = pd.DataFrame({
    'NOM_COURT': ['MERC_E', 'MODUS', 'MONDEO', 'MURANO', 'MUSA', 'OUTLAND', 'P1007',
                  'P307CC', 'P407', 'P607', 'PANDA', 'PASSAT', 'PTCRUISER', 'SANTA_FE',
                  'TAHOE', 'TWINGO', 'VECTRA', 'VELSATIS', 'X-TRAIL', 'YARIS'],
    'PUISSANCE': [204, 113, 145, 234, 100, 202, 75, 180, 136, 204, 54, 150, 223, 125,
                  290, 60, 150, 150, 136, 65],
    'CYLINDREE': [3222, 1598, 1999, 3498, 1910, 1997, 1360, 1997, 1997, 2721, 1108,
                  1781, 2429, 1991, 5327, 1149, 1910, 2188, 2184, 998],
    'VITESSE': [243, 188, 215, 200, 179, 220, 165, 225, 212, 230, 150, 221, 200, 172,
                170, 151, 217, 200, 180, 155],
    'LONGUEUR': [482, 380, 474, 477, 399, 455, 374, 435, 468, 491, 354, 471, 429, 450,
                 506, 344, 460, 486, 446, 364],
    'LARGEUR': [183, 170, 194, 188, 170, 178, 169, 176, 182, 184, 159, 175, 171, 185,
                223, 163, 180, 186, 177, 166]
})

df4 = pd.DataFrame({
    'NOM_COURT': ['MERC_E', 'MODUS', 'MONDEO', 'MURANO', 'MUSA', 'OUTLAND', 'P1007',
                  'P307CC', 'P407', 'P607', 'PANDA', 'PASSAT', 'PTCRUISER', 'SANTA_FE',
                  'TAHOE', 'TWINGO', 'VECTRA', 'VELSATIS', 'X-TRAIL', 'YARIS'],
    'HAUTEUR': [146, 159, 143, 171, 169, 167, 161, 143, 145, 145, 154, 147, 154, 173,
                196, 143, 146, 158, 168, 150],
    'POIDS': [1735, 1170, 1378, 1870, 1275, 1595, 1181, 1490, 1415, 1723, 860, 1360,
              1595, 1757, 2463, 840, 1428, 1735, 1520, 880],
    'COFFRE': [520, 198, 500, 438, 320, 402, 178, 204, 407, 468, 206, 475, 210, 833,
               460, 168, 500, 460, 350, 205],
    'RESERVOIR': [80, 49, 59, 82, 47, 60, 50, 50, 66, 80, 35, 62, 57, 65,
                  98, 40, 61, 80, 60, 45],
    'CONSO': [6.9, 6.8, 7.9, 12.3, 5.5, 10, 6.4, 8.8, 8.2, 8.4, 5.7, 8.2, 9.9, 7.5,
              14.3, 6, 5.9, 7.1, 7.2, 5.6],
    'CO2': [183, 163, 189, 295, 146, 237, 153, 210, 194, 223, 135, 197, 235, 197,
            340, 143, 159, 188, 190, 134],
    'PRIX': [46450, 16950, 23100, 44000, 17900, 29990, 13600, 28850, 23400, 40550,
             8070, 27740, 27400, 27990, 49600, 8950, 26550, 38250, 29700, 10450]
})

# Concaténation des deux parties
df1_complet = pd.merge(df1, df2, on='NOM_COURT')
df2_complet = pd.merge(df3, df4, on='NOM_COURT')

# Fusion finale
df_autos = pd.concat([df1_complet, df2_complet], ignore_index=True)

df_autos = df_autos.rename(columns={
    'PUISSANCE': 'PUISS',
    'CYLINDREE': 'CYLIN',
    'VITESSE': 'VITES',
    'LONGUEUR': 'LONG',
    'LARGEUR': 'LARG',
    'HAUTEUR': 'HAUT',
    'RESERVOIR': 'RESERV'
})

colonnes_numeriques = ['PUISS', 'CYLIN', 'VITES', 'LONG', 'LARG', 'HAUT', 'POIDS', 'COFFRE', 'RESERV', 'CONSO', 'CO2', 'PRIX']
df_num = df_autos[colonnes_numeriques].copy()

print(df_num.head())
print(f"\nDimensions : {df_num.shape}")

# Standardisation
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_num)
df_scaled = pd.DataFrame(df_scaled, columns=colonnes_numeriques)

print("Statistiques après standardisation (moyenne ≈ 0, écart-type ≈ 1) :")
print(df_scaled.describe().round(2))

# Création du modèle ACP
pca = PCA()
pca_result = pca.fit_transform(df_scaled)

# Création d'un DataFrame avec les coordonnées des individus
df_pca = pd.DataFrame(pca_result,  columns=[f'PC{i+1}' for i in range(pca_result.shape[1])])
df_pca['NOM_COURT'] = df_autos['NOM_COURT']

print("Premières coordonnées des individus sur les axes :")
print(df_pca.head())

# Analyse des valeurs propres (inertie)
inertie_expliquee = pca.explained_variance_ratio_
inertie_cumulee = np.cumsum(inertie_expliquee)

#Creation de tableau de récapitulation
variance_df = pd.DataFrame({
    'Composante': [f'PC{i+1}' for i in range(len(inertie_expliquee))],
    'Valeur propre': pca.explained_variance_,
    '% Inertie expliquée': inertie_expliquee * 100,
    '% Cumulé': inertie_cumulee * 100
})

print("\n**** TABLEAU DES VALEURS PROPRES *****")
print(variance_df.round(2))

# Graphique des valeurs propres
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.bar(range(1, len(inertie_expliquee) + 1), inertie_expliquee * 100,
        alpha=0.7, color='steelblue', edgecolor='black')
plt.plot(range(1, len(inertie_expliquee) + 1), inertie_expliquee * 100,
         'ro-', linewidth=2, markersize=8)
plt.xlabel('Composantes principales', fontsize=12)
plt.ylabel('Pourcentage d\'inertie expliquée', fontsize=12)
plt.title('Éboulis des valeurs propres', fontsize=14, fontweight='bold')
plt.grid(True, alpha=0.3)
plt.xticks(range(1, len(inertie_expliquee) + 1))

plt.subplot(1, 2, 2)
plt.plot(range(1, len(inertie_cumulee) + 1), inertie_cumulee * 100,
         'bo-', linewidth=2, markersize=8)
plt.fill_between(range(1, len(inertie_cumulee) + 1), 0, inertie_cumulee * 100,
                 alpha=0.3, color='steelblue')
plt.xlabel('Composantes principales', fontsize=12)
plt.ylabel('Pourcentage d\'inertie cumulée', fontsize=12)
plt.title('Inertie cumulée', fontsize=14, fontweight='bold')
plt.grid(True, alpha=0.3)
plt.axhline(y=80, color='red', linestyle='--', alpha=0.7, label='Seuil 80%')
plt.legend()
plt.xticks(range(1, len(inertie_cumulee) + 1))

plt.tight_layout()
plt.show()

print(f"\nLes {variance_df['Composante'][0:3].tolist()} expliquent {inertie_cumulee[2]*100:.1f}% de l'inertie totale")

# Calcul des corrélations entre variables originales et composantes
correlations = pd.DataFrame(
    pca.components_.T * np.sqrt(pca.explained_variance_),
    columns=[f'PC{i+1}' for i in range(pca.n_components_)],
    index=colonnes_numeriques
)

# Pour vérifier (les carrés des cos²)
cos2 = correlations**2

print("\n**** CORRÉLATIONS VARIABLES - AXES ****")
print("Ces valeurs sont les coordonnées pour le cercle des corrélations")
print(correlations.round(3))

print("\n**** COSINUS CARRÉS (qualité de représentation) *****")
print(cos2.round(3))

#tracé du cercle de corrélation
def plot_cercle_correlations(correlations, axe_x=0, axe_y=1, titre="Cercle des corrélations"):

    fig, ax = plt.subplots(figsize=(10, 10))
    cercle = plt.Circle((0, 0), 1, fill=False, edgecolor='black', linewidth=1.5, linestyle='-', alpha=0.7)
    ax.add_patch(cercle)

    ax.axhline(y=0, color='gray', linestyle='-', linewidth=0.5, alpha=0.5)
    ax.axvline(x=0, color='gray', linestyle='-', linewidth=0.5, alpha=0.5)

    for i, var in enumerate(correlations.index):
        x = correlations.iloc[i, axe_x]
        y = correlations.iloc[i, axe_y]

        distance = np.sqrt(x**2 + y**2)
        if distance > 0.5:
            couleur = 'darkred'
            alpha = 1.0
            linewidth = 1.5
        elif distance > 0.3:
            couleur = 'coral'
            alpha = 0.8
            linewidth = 1.2
        else:
            couleur = 'lightcoral'
            alpha = 0.6
            linewidth = 1.0

        # Tracé de la flèche
        ax.arrow(0, 0, x, y,
                 head_width=0.03, head_length=0.03,
                 fc=couleur, ec=couleur, alpha=alpha, linewidth=linewidth)

        ax.annotate(var, (x, y),
                   xytext=(x + 0.02 * np.sign(x), y + 0.02 * np.sign(y)),
                   fontsize=10, fontweight='bold',
                   color='darkblue', alpha=1.0,
                   bbox=dict(boxstyle="round,pad=0.2", facecolor="white", alpha=0.8, edgecolor="none"))

    ax.set_xlim(-1.1, 1.1)
    ax.set_ylim(-1.1, 1.1)
    ax.set_aspect('equal')
    ax.set_xlabel(f'Axe {axe_x+1} ({inertie_expliquee[axe_x]*100:.1f}%)', fontsize=12, fontweight='bold')
    ax.set_ylabel(f'Axe {axe_y+1} ({inertie_expliquee[axe_y]*100:.1f}%)', fontsize=12, fontweight='bold')
    ax.set_title(titre, fontsize=14, fontweight='bold')

    # Grille
    ax.grid(True, alpha=0.3, linestyle='--')

    for r in [0.5, 0.7]:
        cercle_inter = plt.Circle((0, 0), r, fill=False, edgecolor='gray', linewidth=0.5, linestyle='--', alpha=0.3)
        ax.add_patch(cercle_inter)

    plt.tight_layout()
    plt.show()

# Tracé du cercle pour les deux premiers axes
plot_cercle_correlations(correlations, axe_x=0, axe_y=1, titre="Cercle des corrélations - Axes 1 et 2")

# Tracé pour les axes 2 et 3 (si pertinent)
if len(inertie_expliquee) > 2:
    plot_cercle_correlations(correlations, axe_x=1, axe_y=2, titre="Cercle des corrélations - Axes 2 et 3")

# interprétation détaillée

def interpreter_axes(correlations, axe, seuil=0.5):

    corr_axe = correlations.iloc[:, axe]
    print(f"\n----------- INTERPRÉTATION DE L'AXE {axe+1} ------------")
    print(f"Inertie expliquée : {inertie_expliquee[axe]*100:.1f}%")

    # Corrélations positives
    pos = corr_axe[corr_axe > seuil].sort_values(ascending=False)
    if not pos.empty:
        print(f"\nVariables corrélées POSITIVEMENT (r > {seuil}):")
        for var, val in pos.items():
            print(f"  {var}: {val:.3f}")

    # Corrélations négatives
    neg = corr_axe[corr_axe < -seuil].sort_values()
    if not neg.empty:
        print(f"\nVariables corrélées NÉGATIVEMENT (r < -{seuil}):")
        for var, val in neg.items():
            print(f"  {var}: {val:.3f}")

    # Synthèse
    return corr_axe

# Interprétation des 3 premiers axes
print("******* ANALYSE DES AXES PRINCIPAUX *******")
axe1 = interpreter_axes(correlations, 0, seuil=0.6)
axe2 = interpreter_axes(correlations, 1, seuil=0.5)
if len(inertie_expliquee) > 2:
    axe3 = interpreter_axes(correlations, 2, seuil=0.5)

#graphique des individus
def plot_individus(df_pca, axe_x=0, axe_y=1):

    plt.figure(figsize=(12, 8))
    # Tracé des points
    scatter = plt.scatter(df_pca[f'PC{axe_x+1}'], df_pca[f'PC{axe_y+1}'],
                         alpha=0.7, s=80, c='steelblue', edgecolor='black')

    # Ajout des étiquettes
    for i, nom in enumerate(df_pca['NOM_COURT']):
        plt.annotate(nom,
                    (df_pca.iloc[i, axe_x], df_pca.iloc[i, axe_y]),
                    xytext=(5, 5), textcoords='offset points',
                    fontsize=8, alpha=0.8)

    # Axes
    plt.axhline(y=0, color='gray', linestyle='-', linewidth=0.5, alpha=0.5)
    plt.axvline(x=0, color='gray', linestyle='-', linewidth=0.5, alpha=0.5)

    plt.xlabel(f'Axe {axe_x+1} ({inertie_expliquee[axe_x]*100:.1f}%)', fontsize=12)
    plt.ylabel(f'Axe {axe_y+1} ({inertie_expliquee[axe_y]*100:.1f}%)', fontsize=12)
    plt.title('Projection des individus', fontsize=14, fontweight='bold')
    plt.grid(True, alpha=0.3)

    # Ajout des ellipses de concentration
    from matplotlib.patches import Ellipse
    if len(df_pca) > 5:
        # Ellipse à 95% de confiance
        cov = np.cov(df_pca[[f'PC{axe_x+1}', f'PC{axe_y+1}']].T)
        lambda_, v = np.linalg.eig(cov)
        lambda_ = np.sqrt(lambda_)
        ell = Ellipse(xy=(df_pca[f'PC{axe_x+1}'].mean(), df_pca[f'PC{axe_y+1}'].mean()),
                     width=lambda_[0]*2*2, height=lambda_[1]*2*2,
                     angle=np.rad2deg(np.arccos(v[0, 0])),
                     facecolor='none', edgecolor='red', linewidth=2, alpha=0.5)
        plt.gca().add_patch(ell)

    plt.tight_layout()
    plt.show()

# Tracé des individus
plot_individus(df_pca, 0, 1)