# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhKqDfyg1yR8Ok6IgnScUtBabNl4LZHZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#données issues de cours https://maths.cnam.fr/IMG/pdf/1-Introduction_analyse_de_donnees-2013_cle8ba3a2.pdf
# Première table (caractéristiques principales)

df1 = pd.DataFrame({
    'NOM_COURT': ['ALFA 156', 'AUDIA3', 'AUDIA8', 'AVENSIS', 'BMW X5', 'BMW530',
                  'CHRYS300', 'CITRONC2', 'CITRONC4', 'CITRONC5', 'CLIO', 'CORSA',
                  'CORVETTE', 'FIESTA', 'GOLF', 'LAGUNA', 'LANDCRUI', 'MAZDARX8',
                  'MEGANECC', 'MERC_A'],
    'PUISSANCE': [250, 102, 280, 115, 218, 231, 340, 61, 138, 210, 100, 70,
                  404, 68, 75, 165, 204, 231, 165, 140],
    'CYLINDREE': [3179, 1595, 3697, 1995, 2993, 2979, 5654, 1124, 1997, 2496,
                  1461, 1248, 5970, 1399, 1968, 1998, 4164, 1308, 1998, 1991],
    'VITESSE': [250, 185, 250, 195, 210, 250, 250, 158, 207, 230, 185, 165,
                300, 164, 163, 218, 170, 235, 225, 201],
    'LONGUEUR': [443, 421, 506, 463, 467, 485, 502, 367, 426, 475, 382, 384,
                 444, 392, 421, 458, 489, 443, 436, 384],
    'LARGEUR': [175, 177, 203, 176, 188, 185, 188, 166, 178, 178, 164, 165,
                185, 168, 176, 178, 194, 177, 178, 177]
})

# Deuxième table
df2 = pd.DataFrame({
    'NOM_COURT': ['ALFA 156', 'AUDIA3', 'AUDIA8', 'AVENSIS', 'BMW X5', 'BMW530',
                  'CHRYS300', 'CITRONC2', 'CITRONC4', 'CITRONC5', 'CLIO', 'CORSA',
                  'CORVETTE', 'FIESTA', 'GOLF', 'LAGUNA', 'LANDCRUI', 'MAZDARX8',
                  'MEGANECC', 'MERC_A'],
    'HAUTEUR': [141, 143, 145, 148, 172, 147, 148, 147, 146, 148, 142, 144,
                125, 144, 149, 143, 185, 134, 141, 160],
    'POIDS': [1410, 1205, 1770, 1400, 2095, 1495, 1835, 932, 1381, 1589, 980,
              1035, 1517, 1138, 1217, 1320, 2495, 1390, 1415, 1340],
    'COFFRE': [378, 350, 500, 510, 465, 520, 442, 224, 314, 471, 255, 260,
               295, 261, 350, 430, 403, 287, 190, 435],
    'RESERVOIR': [63, 55, 90, 60, 93, 70, 72, 41, 60, 65, 50, 45,
                  69, 45, 55, 70, 96, 61, 60, 54],
    'CONSO': [12.1, 7, 11.7, 5.8, 8.6, 9.5, 12.2, 5.9, 5.4, 10, 4.3, 4.7,
              13, 4.4, 5.4, 8.2, 11.1, 11.4, 8, 5.4],
    'CO2': [287, 168, 281, 155, 229, 231, 291, 141, 142, 238, 113, 127,
            310, 117, 143, 196, 292, 284, 191, 141],
    'PRIX': [40800, 21630, 78340, 26400, 52000, 46400, 54900, 10700, 23400, 33000,
             17600, 13590, 63350, 14150, 19140, 25350, 67100, 34000, 27800, 24550]
})

# Même chose pour les 20 autres voitures
df3 = pd.DataFrame({
    'NOM_COURT': ['MERC_E', 'MODUS', 'MONDEO', 'MURANO', 'MUSA', 'OUTLAND', 'P1007',
                  'P307CC', 'P407', 'P607', 'PANDA', 'PASSAT', 'PTCRUISER', 'SANTA_FE',
                  'TAHOE', 'TWINGO', 'VECTRA', 'VELSATIS', 'X-TRAIL', 'YARIS'],
    'PUISSANCE': [204, 113, 145, 234, 100, 202, 75, 180, 136, 204, 54, 150, 223, 125,
                  290, 60, 150, 150, 136, 65],
    'CYLINDREE': [3222, 1598, 1999, 3498, 1910, 1997, 1360, 1997, 1997, 2721, 1108,
                  1781, 2429, 1991, 5327, 1149, 1910, 2188, 2184, 998],
    'VITESSE': [243, 188, 215, 200, 179, 220, 165, 225, 212, 230, 150, 221, 200, 172,
                170, 151, 217, 200, 180, 155],
    'LONGUEUR': [482, 380, 474, 477, 399, 455, 374, 435, 468, 491, 354, 471, 429, 450,
                 506, 344, 460, 486, 446, 364],
    'LARGEUR': [183, 170, 194, 188, 170, 178, 169, 176, 182, 184, 159, 175, 171, 185,
                223, 163, 180, 186, 177, 166]
})

df4 = pd.DataFrame({
    'NOM_COURT': ['MERC_E', 'MODUS', 'MONDEO', 'MURANO', 'MUSA', 'OUTLAND', 'P1007',
                  'P307CC', 'P407', 'P607', 'PANDA', 'PASSAT', 'PTCRUISER', 'SANTA_FE',
                  'TAHOE', 'TWINGO', 'VECTRA', 'VELSATIS', 'X-TRAIL', 'YARIS'],
    'HAUTEUR': [146, 159, 143, 171, 169, 167, 161, 143, 145, 145, 154, 147, 154, 173,
                196, 143, 146, 158, 168, 150],
    'POIDS': [1735, 1170, 1378, 1870, 1275, 1595, 1181, 1490, 1415, 1723, 860, 1360,
              1595, 1757, 2463, 840, 1428, 1735, 1520, 880],
    'COFFRE': [520, 198, 500, 438, 320, 402, 178, 204, 407, 468, 206, 475, 210, 833,
               460, 168, 500, 460, 350, 205],
    'RESERVOIR': [80, 49, 59, 82, 47, 60, 50, 50, 66, 80, 35, 62, 57, 65,
                  98, 40, 61, 80, 60, 45],
    'CONSO': [6.9, 6.8, 7.9, 12.3, 5.5, 10, 6.4, 8.8, 8.2, 8.4, 5.7, 8.2, 9.9, 7.5,
              14.3, 6, 5.9, 7.1, 7.2, 5.6],
    'CO2': [183, 163, 189, 295, 146, 237, 153, 210, 194, 223, 135, 197, 235, 197,
            340, 143, 159, 188, 190, 134],
    'PRIX': [46450, 16950, 23100, 44000, 17900, 29990, 13600, 28850, 23400, 40550,
             8070, 27740, 27400, 27990, 49600, 8950, 26550, 38250, 29700, 10450]
})

# Concaténation des deux parties
df1_complet = pd.merge(df1, df2, on='NOM_COURT')
df2_complet = pd.merge(df3, df4, on='NOM_COURT')

# Fusion finale
df_autos = pd.concat([df1_complet, df2_complet], ignore_index=True)

# Afficher les premières lignes
print("Aperçu des données fusionnées :")
print(df_autos.head())
print(f"\nDimensions du DataFrame : {df_autos.shape}")
print(f"Colonnes : {df_autos.columns.tolist()}")

# 1. Vérifier les valeurs manquantes
print("\nValeurs manquantes par colonne :")
print(df_autos.isnull().sum())

# 2. Vérifier les types de données
print("\nTypes de données :")
print(df_autos.dtypes)

# 3. Statistiques descriptives rapides
print("\nStatistiques descriptives :")
print(df_autos.describe())

# 4. Optionnel : Renommer les colonnes pour plus de clarté (si besoin)
df_autos = df_autos.rename(columns={
    'PUISSANCE': 'PUISS',
    'CYLINDREE': 'CYLIN',
    'VITESSE': 'VITES',
    'LONGUEUR': 'LONG',
    'LARGEUR': 'LARG',
    'HAUTEUR': 'HAUT',
    'RESERVOIR': 'RESERV'
})

# les colonnes numériques
colonnes_numeriques = ['PUISS', 'CYLIN', 'VITES', 'LONG', 'LARG', 'HAUT', 'POIDS', 'COFFRE', 'RESERV', 'CONSO', 'CO2', 'PRIX']
df_numerique = df_autos[colonnes_numeriques]

# Méthode 1 : Calcul direct avec pandas
matrice_correlation = df_numerique.corr()

print("\n MATRICE DE CORRÉLATION (avec pandas) ")
print(matrice_correlation.round(3))

# la figure
plt.figure(figsize=(12, 10))

# seaborn
sns.heatmap(matrice_correlation,
            annot=True,           # Afficher les valeurs
            fmt='.3f',            # Format à 3 décimales
            cmap='RdBu_r',        # Dégradé de couleur (rouge/bleu)
            center=0,             # Centre de la colormap à 0
            vmin=-1, vmax=1,      # Bornes de corrélation
            square=True,           # Cellules carrées
            linewidths=0.5,        # Lignes de séparation
            cbar_kws={"shrink": 0.8})  # Taille de la colorbar

plt.title('Matrice de corrélation - Données Automobiles', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

# 1. Extraire les paires de variables les plus corrélées
corr_pairs = matrice_correlation.unstack().sort_values(ascending=False)
corr_pairs = corr_pairs[corr_pairs < 1]  # Enlever les auto-corrélations
print("\nTop 10 des corrélations les plus fortes :")
print(corr_pairs.head(10))

# 2. Identifier les variables faiblement corrélées
print("\nVariables faiblement corrélées (|r| < 0.2) :")
faibles_corr = corr_pairs[abs(corr_pairs) < 0.2]
print(faibles_corr)

# 3. Test de significativité (optionnel - approche statistique)
from scipy import stats

def calculer_pvalue(df):
    """Calcule les p-values des corrélations"""
    p_values = pd.DataFrame(np.zeros_like(matrice_correlation),
                           index=matrice_correlation.index,
                           columns=matrice_correlation.columns)
    for i in range(len(df.columns)):
        for j in range(i+1, len(df.columns)):
            _, p_value = stats.pearsonr(df.iloc[:, i], df.iloc[:, j])
            p_values.iloc[i, j] = p_value
            p_values.iloc[j, i] = p_value
    return p_values

p_values = calculer_pvalue(df_numerique)
print("\nP-values des corrélations (seuil de significativité α=0.05) :")
print(p_values.round(4))

# Sauvegarder la matrice de corrélation dans un fichier CSV
matrice_correlation.to_csv('matrice_correlation_autos.csv')
print("\nMatrice de corrélation sauvegardée dans 'matrice_correlation_autos.csv'")

# Sauvegarder également les données fusionnées
df_autos.to_csv('donnees_autos_completes.csv', index=False)
print("Données complètes sauvegardées dans 'donnees_autos_completes.csv'")