# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkiEPiMCnBr1mwyRE6akaZ-17vU-sMVp
"""

# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhKqDfyg1yR8Ok6IgnScUtBabNl4LZHZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#données issues de cours https://maths.cnam.fr/IMG/pdf/1-Introduction_analyse_de_donnees-2013_cle8ba3a2.pdf
# Première table (caractéristiques principales)

df1 = pd.DataFrame({
    'NOM_COURT': ['ALFA 156', 'AUDIA3', 'AUDIA8', 'AVENSIS', 'BMW X5', 'BMW530',
                  'CHRYS300', 'CITRONC2', 'CITRONC4', 'CITRONC5', 'CLIO', 'CORSA',
                  'CORVETTE', 'FIESTA', 'GOLF', 'LAGUNA', 'LANDCRUI', 'MAZDARX8',
                  'MEGANECC', 'MERC_A'],
    'PUISSANCE': [250, 102, 280, 115, 218, 231, 340, 61, 138, 210, 100, 70,
                  404, 68, 75, 165, 204, 231, 165, 140],
    'CYLINDREE': [3179, 1595, 3697, 1995, 2993, 2979, 5654, 1124, 1997, 2496,
                  1461, 1248, 5970, 1399, 1968, 1998, 4164, 1308, 1998, 1991],
    'VITESSE': [250, 185, 250, 195, 210, 250, 250, 158, 207, 230, 185, 165,
                300, 164, 163, 218, 170, 235, 225, 201],
    'LONGUEUR': [443, 421, 506, 463, 467, 485, 502, 367, 426, 475, 382, 384,
                 444, 392, 421, 458, 489, 443, 436, 384],
    'LARGEUR': [175, 177, 203, 176, 188, 185, 188, 166, 178, 178, 164, 165,
                185, 168, 176, 178, 194, 177, 178, 177]
})

# Deuxième table
df2 = pd.DataFrame({
    'NOM_COURT': ['ALFA 156', 'AUDIA3', 'AUDIA8', 'AVENSIS', 'BMW X5', 'BMW530',
                  'CHRYS300', 'CITRONC2', 'CITRONC4', 'CITRONC5', 'CLIO', 'CORSA',
                  'CORVETTE', 'FIESTA', 'GOLF', 'LAGUNA', 'LANDCRUI', 'MAZDARX8',
                  'MEGANECC', 'MERC_A'],
    'HAUTEUR': [141, 143, 145, 148, 172, 147, 148, 147, 146, 148, 142, 144,
                125, 144, 149, 143, 185, 134, 141, 160],
    'POIDS': [1410, 1205, 1770, 1400, 2095, 1495, 1835, 932, 1381, 1589, 980,
              1035, 1517, 1138, 1217, 1320, 2495, 1390, 1415, 1340],
    'COFFRE': [378, 350, 500, 510, 465, 520, 442, 224, 314, 471, 255, 260,
               295, 261, 350, 430, 403, 287, 190, 435],
    'RESERVOIR': [63, 55, 90, 60, 93, 70, 72, 41, 60, 65, 50, 45,
                  69, 45, 55, 70, 96, 61, 60, 54],
    'CONSO': [12.1, 7, 11.7, 5.8, 8.6, 9.5, 12.2, 5.9, 5.4, 10, 4.3, 4.7,
              13, 4.4, 5.4, 8.2, 11.1, 11.4, 8, 5.4],
    'CO2': [287, 168, 281, 155, 229, 231, 291, 141, 142, 238, 113, 127,
            310, 117, 143, 196, 292, 284, 191, 141],
    'PRIX': [40800, 21630, 78340, 26400, 52000, 46400, 54900, 10700, 23400, 33000,
             17600, 13590, 63350, 14150, 19140, 25350, 67100, 34000, 27800, 24550]
})

# Même chose pour les 20 autres voitures
df3 = pd.DataFrame({
    'NOM_COURT': ['MERC_E', 'MODUS', 'MONDEO', 'MURANO', 'MUSA', 'OUTLAND', 'P1007',
                  'P307CC', 'P407', 'P607', 'PANDA', 'PASSAT', 'PTCRUISER', 'SANTA_FE',
                  'TAHOE', 'TWINGO', 'VECTRA', 'VELSATIS', 'X-TRAIL', 'YARIS'],
    'PUISSANCE': [204, 113, 145, 234, 100, 202, 75, 180, 136, 204, 54, 150, 223, 125,
                  290, 60, 150, 150, 136, 65],
    'CYLINDREE': [3222, 1598, 1999, 3498, 1910, 1997, 1360, 1997, 1997, 2721, 1108,
                  1781, 2429, 1991, 5327, 1149, 1910, 2188, 2184, 998],
    'VITESSE': [243, 188, 215, 200, 179, 220, 165, 225, 212, 230, 150, 221, 200, 172,
                170, 151, 217, 200, 180, 155],
    'LONGUEUR': [482, 380, 474, 477, 399, 455, 374, 435, 468, 491, 354, 471, 429, 450,
                 506, 344, 460, 486, 446, 364],
    'LARGEUR': [183, 170, 194, 188, 170, 178, 169, 176, 182, 184, 159, 175, 171, 185,
                223, 163, 180, 186, 177, 166]
})

df4 = pd.DataFrame({
    'NOM_COURT': ['MERC_E', 'MODUS', 'MONDEO', 'MURANO', 'MUSA', 'OUTLAND', 'P1007',
                  'P307CC', 'P407', 'P607', 'PANDA', 'PASSAT', 'PTCRUISER', 'SANTA_FE',
                  'TAHOE', 'TWINGO', 'VECTRA', 'VELSATIS', 'X-TRAIL', 'YARIS'],
    'HAUTEUR': [146, 159, 143, 171, 169, 167, 161, 143, 145, 145, 154, 147, 154, 173,
                196, 143, 146, 158, 168, 150],
    'POIDS': [1735, 1170, 1378, 1870, 1275, 1595, 1181, 1490, 1415, 1723, 860, 1360,
              1595, 1757, 2463, 840, 1428, 1735, 1520, 880],
    'COFFRE': [520, 198, 500, 438, 320, 402, 178, 204, 407, 468, 206, 475, 210, 833,
               460, 168, 500, 460, 350, 205],
    'RESERVOIR': [80, 49, 59, 82, 47, 60, 50, 50, 66, 80, 35, 62, 57, 65,
                  98, 40, 61, 80, 60, 45],
    'CONSO': [6.9, 6.8, 7.9, 12.3, 5.5, 10, 6.4, 8.8, 8.2, 8.4, 5.7, 8.2, 9.9, 7.5,
              14.3, 6, 5.9, 7.1, 7.2, 5.6],
    'CO2': [183, 163, 189, 295, 146, 237, 153, 210, 194, 223, 135, 197, 235, 197,
            340, 143, 159, 188, 190, 134],
    'PRIX': [46450, 16950, 23100, 44000, 17900, 29990, 13600, 28850, 23400, 40550,
             8070, 27740, 27400, 27990, 49600, 8950, 26550, 38250, 29700, 10450]
})

# Concaténation des deux parties
df1_complet = pd.merge(df1, df2, on='NOM_COURT')
df2_complet = pd.merge(df3, df4, on='NOM_COURT')

# Fusion finale
df_autos = pd.concat([df1_complet, df2_complet], ignore_index=True)

# Afficher les premières lignes
print("Aperçu des données fusionnées :")
print(df_autos.head())
print(f"\nDimensions du DataFrame : {df_autos.shape}")
print(f"Colonnes : {df_autos.columns.tolist()}")

# 1. Vérifier les valeurs manquantes
print("\nValeurs manquantes par colonne :")
print(df_autos.isnull().sum())

# 2. Vérifier les types de données
print("\nTypes de données :")
print(df_autos.dtypes)

# 3. Statistiques descriptives rapides
print("\nStatistiques descriptives :")
print(df_autos.describe())

# 4. Optionnel : Renommer les colonnes pour plus de clarté (si besoin)
df_autos = df_autos.rename(columns={
    'PUISSANCE': 'PUISS',
    'CYLINDREE': 'CYLIN',
    'VITESSE': 'VITES',
    'LONGUEUR': 'LONG',
    'LARGEUR': 'LARG',
    'HAUTEUR': 'HAUT',
    'RESERVOIR': 'RESERV'
})

# les colonnes numériques
colonnes_numeriques = ['PUISS', 'CYLIN', 'VITES', 'LONG', 'LARG', 'HAUT', 'POIDS', 'COFFRE', 'RESERV', 'CONSO', 'CO2', 'PRIX']
df_numerique = df_autos[colonnes_numeriques]

# Méthode 1 : Calcul direct avec pandas
matrice_correlation = df_numerique.corr()

print("\n MATRICE DE CORRÉLATION (avec pandas) ")
print(matrice_correlation.round(3))

# la figure
plt.figure(figsize=(12, 10))

# seaborn
sns.heatmap(matrice_correlation,
            annot=True,           # Afficher les valeurs
            fmt='.3f',            # Format à 3 décimales
            cmap='RdBu_r',        # Dégradé de couleur (rouge/bleu)
            center=0,             # Centre de la colormap à 0
            vmin=-1, vmax=1,      # Bornes de corrélation
            square=True,           # Cellules carrées
            linewidths=0.5,        # Lignes de séparation
            cbar_kws={"shrink": 0.8})  # Taille de la colorbar

plt.title('Matrice de corrélation - Données Automobiles', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

# 1. Extraire les paires de variables les plus corrélées
corr_pairs = matrice_correlation.unstack().sort_values(ascending=False)
corr_pairs = corr_pairs[corr_pairs < 1]  # Enlever les auto-corrélations
print("\nTop 10 des corrélations les plus fortes :")
print(corr_pairs.head(10))

# 2. Identifier les variables faiblement corrélées
print("\nVariables faiblement corrélées (|r| < 0.2) :")
faibles_corr = corr_pairs[abs(corr_pairs) < 0.2]
print(faibles_corr)

# 3. Test de significativité (optionnel - approche statistique)
from scipy import stats

def calculer_pvalue(df):
    """Calcule les p-values des corrélations"""
    p_values = pd.DataFrame(np.zeros_like(matrice_correlation),
                           index=matrice_correlation.index,
                           columns=matrice_correlation.columns)
    for i in range(len(df.columns)):
        for j in range(i+1, len(df.columns)):
            _, p_value = stats.pearsonr(df.iloc[:, i], df.iloc[:, j])
            p_values.iloc[i, j] = p_value
            p_values.iloc[j, i] = p_value
    return p_values

p_values = calculer_pvalue(df_numerique)
print("\nP-values des corrélations (seuil de significativité α=0.05) :")
print(p_values.round(4))

# Sauvegarder la matrice de corrélation dans un fichier CSV
matrice_correlation.to_csv('matrice_correlation_autos.csv')
print("\nMatrice de corrélation sauvegardée dans 'matrice_correlation_autos.csv'")

# Sauvegarder également les données fusionnées
df_autos.to_csv('donnees_autos_completes.csv', index=False)
print("Données complètes sauvegardées dans 'donnees_autos_completes.csv'")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import statsmodels.api as sm

# Préparation des données
# Objectif : Prédire PRIX à partir des autres variables numériques
variables_explicatives = ['PUISS', 'CYLIN', 'VITES', 'LONG', 'LARG', 'HAUT', 'POIDS', 'COFFRE', 'RESERV', 'CONSO', 'CO2']
X = df_autos[variables_explicatives]
y = df_autos['PRIX']

# Division train/test (70% - 30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Taille entraînement : {len(X_train)} observations")
print(f"Taille test : {len(X_test)} observations")

# Modèle de régression linéaire
reg = LinearRegression()
reg.fit(X_train, y_train)

# Prédictions
y_pred_train = reg.predict(X_train)
y_pred_test = reg.predict(X_test)

# Évaluation
print("\n******** PERFORMANCE DU MODÈLE ******")
print(f"R² (entraînement) : {r2_score(y_train, y_pred_train):.3f}")
print(f"R² (test) : {r2_score(y_test, y_pred_test):.3f}")
print(f"RMSE (test) : {np.sqrt(mean_squared_error(y_test, y_pred_test)):.0f} €")
print(f"MAE (test) : {mean_absolute_error(y_test, y_pred_test):.0f} €")

# Affichage des coefficients
coefs = pd.DataFrame({
    'Variable': variables_explicatives,
    'Coefficient': reg.coef_,
    'Valeur_abs': np.abs(reg.coef_)
}).sort_values('Valeur_abs', ascending=False)

print("\n******* IMPORTANCE DES VARIABLES *********")
print(coefs.to_string(index=False))

# Modèle avec statsmodels pour plus de détails statistiques
X_train_sm = sm.add_constant(X_train)  # Ajout de l'intercept
modele_sm = sm.OLS(y_train, X_train_sm).fit()

print(modele_sm.summary())

# Analyse des résidus
residus = modele_sm.resid
plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.scatter(modele_sm.fittedvalues, residus, alpha=0.6)
plt.axhline(y=0, color='red', linestyle='--')
plt.xlabel('Valeurs prédites')
plt.ylabel('Résidus')
plt.title('Résidus vs Prédictions')

plt.subplot(1, 3, 2)
plt.hist(residus, bins=20, edgecolor='black', alpha=0.7)
plt.xlabel('Résidus')
plt.ylabel('Fréquence')
plt.title('Distribution des résidus')

plt.subplot(1, 3, 3)
sm.qqplot(residus, line='s', ax=plt.gca())
plt.title('Q-Q Plot')

plt.tight_layout()
plt.show()

# visualisation de la qualité de prédiction
plt.figure(figsize=(10, 6))

# Prédictions vs valeurs réelles (test)
plt.scatter(y_test, y_pred_test, alpha=0.7, s=80, c='steelblue', edgecolor='black')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         'r--', linewidth=2, label='Prédiction parfaite')

# Ajout des noms des voitures
for i, nom in enumerate(df_autos.iloc[X_test.index]['NOM_COURT']):
    plt.annotate(nom, (y_test.iloc[i], y_pred_test[i]),
                xytext=(5, 5), textcoords='offset points', fontsize=8)

plt.xlabel('Prix réel (€)', fontsize=12)
plt.ylabel('Prix prédit (€)', fontsize=12)
plt.title('Régression linéaire - Prédiction du prix des voitures',
          fontsize=14, fontweight='bold')
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()
plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc

# Création d'une variable cible binaire
# On définit "sportive" comme: PUISS > 200 et VITESSE > 220
df_autos['SPORTIVE'] = ((df_autos['PUISS'] > 200) & (df_autos['VITES'] > 220)).astype(int)

print("Répartition des classes:")
print(df_autos['SPORTIVE'].value_counts())
print(f"Sportives: {df_autos['SPORTIVE'].sum()} voitures")
print(f"Non sportives: {len(df_autos) - df_autos['SPORTIVE'].sum()} voitures")

# Variables explicatives
X_class = df_autos[['PUISS', 'POIDS', 'CYLIN', 'CONSO']]
y_class = df_autos['SPORTIVE']

# Division train/test
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_class, y_class, test_size=0.3, random_state=42, stratify=y_class
)

# Standardisation (important pour la régression logistique)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_c)
X_test_scaled = scaler.transform(X_test_c)

# Modèle de régression logistique
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train_scaled, y_train_c)

# Prédictions
y_pred_c = log_reg.predict(X_test_scaled)
y_proba_c = log_reg.predict_proba(X_test_scaled)[:, 1]

# Évaluation
print("\n=== MATRICE DE CONFUSION ===")
print(confusion_matrix(y_test_c, y_pred_c))

print("\n=== RAPPORT DE CLASSIFICATION ===")
print(classification_report(y_test_c, y_pred_c,
                          target_names=['Non Sportive', 'Sportive']))

# Courbe ROC
fpr, tpr, thresholds = roc_curve(y_test_c, y_proba_c)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2,
         label=f'Courbe ROC (AUC = {roc_auc:.3f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Aléatoire')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Taux de faux positifs (1 - Spécificité)', fontsize=12)
plt.ylabel('Taux de vrais positifs (Sensibilité)', fontsize=12)
plt.title('Courbe ROC - Classification Sportive', fontsize=14, fontweight='bold')
plt.legend(loc="lower right")
plt.grid(True, alpha=0.3)
plt.show()

# Interprétation des coefficients
coef_log = pd.DataFrame({
    'Variable': X_class.columns,
    'Coefficient': log_reg.coef_[0],
    'Odds Ratio': np.exp(log_reg.coef_[0])
}).sort_values('Coefficient', ascending=False)

print("\n=== COEFFICIENTS DU MODÈLE ===")
print(coef_log.to_string(index=False))

from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, plot_tree
from sklearn.tree import export_text

# Arbre de classification
tree_clf = DecisionTreeClassifier(max_depth=3, random_state=42)
tree_clf.fit(X_train_c, y_train_c)

# Visualisation de l'arbre
plt.figure(figsize=(20, 10))
plot_tree(tree_clf,
          feature_names=X_class.columns,
          class_names=['Non Sportive', 'Sportive'],
          filled=True,
          rounded=True,
          fontsize=10)
plt.title('Arbre de décision - Classification Sportive', fontsize=14, fontweight='bold')
plt.show()

# Version texte (plus lisible)
print(export_text(tree_clf, feature_names=list(X_class.columns)))

# Performance
y_pred_tree = tree_clf.predict(X_test_c)
print("\n=== PERFORMANCE ARBRE ===")
print(classification_report(y_test_c, y_pred_tree,
                          target_names=['Non Sportive', 'Sportive']))

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

# Pour la régression (prédiction du prix)
rf_reg = RandomForestRegressor(n_estimators=100, max_depth=10,
                                random_state=42, n_jobs=-1)
rf_reg.fit(X_train, y_train)

# Prédictions
y_pred_rf = rf_reg.predict(X_test)

print("=== RANDOM FOREST - RÉGRESSION ===")
print(f"R² : {r2_score(y_test, y_pred_rf):.3f}")
print(f"RMSE : {np.sqrt(mean_squared_error(y_test, y_pred_rf)):.0f} €")

# Importance des variables
importance_rf = pd.DataFrame({
    'Variable': X.columns,
    'Importance': rf_reg.feature_importances_
}).sort_values('Importance', ascending=False)

plt.figure(figsize=(10, 6))
plt.barh(importance_rf['Variable'], importance_rf['Importance'],
         color='steelblue', edgecolor='black')
plt.xlabel('Importance', fontsize=12)
plt.ylabel('Variable', fontsize=12)
plt.title('Importance des variables - Random Forest', fontsize=14, fontweight='bold')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

# Pour la classification
rf_clf = RandomForestClassifier(n_estimators=100, max_depth=5,
                                 random_state=42, n_jobs=-1)
rf_clf.fit(X_train_scaled, y_train_c)

y_pred_rf_c = rf_clf.predict(X_test_scaled)
print("\n=== RANDOM FOREST - CLASSIFICATION ===")
print(classification_report(y_test_c, y_pred_rf_c,
                          target_names=['Non Sportive', 'Sportive']))

# Installation: pip install xgboost lightgbm
import xgboost as xgb
import lightgbm as lgb

# XGBoost pour la régression
xgb_reg = xgb.XGBRegressor(n_estimators=100, max_depth=5, learning_rate=0.1, random_state=42)
xgb_reg.fit(X_train, y_train)

y_pred_xgb = xgb_reg.predict(X_test)
print("=== XGBOOST - RÉGRESSION ===")
print(f"R² : {r2_score(y_test, y_pred_xgb):.3f}")
print(f"RMSE : {np.sqrt(mean_squared_error(y_test, y_pred_xgb)):.0f} €")

# LightGBM pour la classification
lgb_clf = lgb.LGBMClassifier(n_estimators=100, max_depth=5, learning_rate=0.1, random_state=42)
lgb_clf.fit(X_train_scaled, y_train_c)

y_pred_lgb = lgb_clf.predict(X_test_scaled)
print("\n=== LIGHTGBM - CLASSIFICATION ===")
print(classification_report(y_test_c, y_pred_lgb, target_names=['Non Sportive', 'Sportive']))

#approche professionnelle comparaison des modèles
def benchmark_modeles(X_train, X_test, y_train, y_test, tache='regression'):

    from sklearn.linear_model import LinearRegression, LogisticRegression
    from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
    from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
    from sklearn.svm import SVR, SVC
    from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, f1_score, roc_auc_score

    if tache == 'regression':
        modeles = {
            'Régression Linéaire': LinearRegression(),
            'Arbre de décision': DecisionTreeRegressor(max_depth=5, random_state=42),
            'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
            'XGBoost': xgb.XGBRegressor(n_estimators=100, random_state=42),
            'SVR': SVR(kernel='rbf')
        }
        metriques = ['R²', 'RMSE', 'MAE']
    else:
        modeles = {
            'Régression Logistique': LogisticRegression(random_state=42),
            'Arbre de décision': DecisionTreeClassifier(max_depth=5, random_state=42),
            'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
            'XGBoost': xgb.XGBClassifier(n_estimators=100, random_state=42),
            'SVM': SVC(kernel='rbf', probability=True, random_state=42)
        }
        metriques = ['Accuracy', 'F1-score', 'AUC']

    results = {}

    for nom, modele in modeles.items():
        # Entraînement
        modele.fit(X_train, y_train)

        # Prédictions
        y_pred = modele.predict(X_test)

        if tache == 'regression':
            results[nom] = {
                'R²': r2_score(y_test, y_pred),
                'RMSE': np.sqrt(mean_squared_error(y_test, y_pred)),
                'MAE': mean_absolute_error(y_test, y_pred)
            }
        else:
            # Pour l'AUC, besoin des probabilités
            if hasattr(modele, 'predict_proba'):
                y_proba = modele.predict_proba(X_test)[:, 1]
                auc_score = roc_auc_score(y_test, y_proba)
            else:
                auc_score = np.nan

            results[nom] = {
                'Accuracy': accuracy_score(y_test, y_pred),
                'F1-score': f1_score(y_test, y_pred, average='weighted'),
                'AUC': auc_score
            }

    # Affichage des résultats
    df_results = pd.DataFrame(results).T
    print(f"\n=== BENCHMARK DES MODÈLES - {tache.upper()} ===")
    print(df_results.round(3))

    # Visualisation
    fig, axes = plt.subplots(1, len(metriques), figsize=(5*len(metriques), 5))

    for i, metrique in enumerate(metriques):
        valeurs = df_results[metrique].sort_values(ascending=False)
        axes[i].barh(valeurs.index, valeurs.values, color='steelblue', edgecolor='black')
        axes[i].set_xlabel(metrique)
        axes[i].set_title(f'Comparaison - {metrique}')
        axes[i].grid(True, alpha=0.3, axis='x')

    plt.tight_layout()
    plt.show()

    return df_results

# Application
resultats_reg = benchmark_modeles(X_train, X_test, y_train, y_test, 'regression')
resultats_clf = benchmark_modeles(X_train_scaled, X_test_scaled, y_train_c, y_test_c, 'classification')

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

# Optimisation pour Random Forest
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [5, 10, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

rf = RandomForestRegressor(random_state=42, n_jobs=-1)

# Grid Search avec validation croisée
grid_search = GridSearchCV(
    rf, param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

print("=== OPTIMISATION DES HYPERPARAMÈTRES ===")
print(f"Meilleurs paramètres : {grid_search.best_params_}")
print(f"Meilleur score CV : {grid_search.best_score_:.3f}")

# Évaluation sur test
best_rf = grid_search.best_estimator_
y_pred_best = best_rf.predict(X_test)
print(f"R² sur test : {r2_score(y_test, y_pred_best):.3f}")

#Optimisation des hyperparamètres grid Search
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

# Optimisation pour Random Forest
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [5, 10, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

rf = RandomForestRegressor(random_state=42, n_jobs=-1)

# Grid Search avec validation croisée
grid_search = GridSearchCV(
    rf, param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

print("=== OPTIMISATION DES HYPERPARAMÈTRES ===")
print(f"Meilleurs paramètres : {grid_search.best_params_}")
print(f"Meilleur score CV : {grid_search.best_score_:.3f}")

# Évaluation sur test
best_rf = grid_search.best_estimator_
y_pred_best = best_rf.predict(X_test)
print(f"R² sur test : {r2_score(y_test, y_pred_best):.3f}")

#validation croisée et courbes d'apprentissage
from sklearn.model_selection import learning_curve, cross_val_score

def courbes_apprentissage(estimator, X, y, cv=5):
    """
    Trace les courbes d'apprentissage pour détecter under/overfitting
    """
    train_sizes, train_scores, test_scores = learning_curve(
        estimator, X, y, cv=cv, n_jobs=-1,
        train_sizes=np.linspace(0.1, 1.0, 10),
        scoring='r2'
    )

    train_mean = np.mean(train_scores, axis=1)
    train_std = np.std(train_scores, axis=1)
    test_mean = np.mean(test_scores, axis=1)
    test_std = np.std(test_scores, axis=1)

    plt.figure(figsize=(10, 6))
    plt.fill_between(train_sizes, train_mean - train_std, train_mean + train_std,
                     alpha=0.1, color='blue')
    plt.fill_between(train_sizes, test_mean - test_std, test_mean + test_std,
                     alpha=0.1, color='red')
    plt.plot(train_sizes, train_mean, 'o-', color='blue', label='Score entraînement')
    plt.plot(train_sizes, test_mean, 'o-', color='red', label='Score validation')
    plt.xlabel('Taille de l\'ensemble d\'entraînement', fontsize=12)
    plt.ylabel('Score R²', fontsize=12)
    plt.title('Courbes d\'apprentissage', fontsize=14, fontweight='bold')
    plt.legend(loc='best')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

# Application sur Random Forest optimisé
courbes_apprentissage(best_rf, X, y)

#Workflow professionnel complet
def pipeline_data_mining(df, target, tache='regression', test_size=0.3):
    """
    Pipeline complet de data mining
    """
    print("=" * 70)
    print("PIPELINE DE DATA MINING")
    print("=" * 70)

    # 1. Séparation des variables
    X = df.drop(columns=[target] + ['NOM_COURT'] if 'NOM_COURT' in df.columns else [target])
    y = df[target]

    # 2. Gestion des valeurs manquantes (si besoin)
    if X.isnull().sum().sum() > 0:
        print("\nTraitement des valeurs manquantes...")
        X = X.fillna(X.median())

    # 3. Encodage des variables catégorielles (si besoin)
    cat_cols = X.select_dtypes(include=['object']).columns
    if len(cat_cols) > 0:
        from sklearn.preprocessing import OneHotEncoder
        from sklearn.compose import ColumnTransformer
        preprocessor = ColumnTransformer(
            transformers=[('cat', OneHotEncoder(drop='first'), cat_cols)],
            remainder='passthrough'
        )
        X = preprocessor.fit_transform(X)

    # 4. Standardisation
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # 5. Division train/test
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=test_size, random_state=42
    )

    # 6. Benchmark des modèles
    print(f"\nTaille train: {len(X_train)}, Taille test: {len(X_test)}")
    results = benchmark_modeles(X_train, X_test, y_train, y_test, tache)

    # 7. Sélection du meilleur modèle
    if tache == 'regression':
        best_model_name = results['R²'].idxmax()
    else:
        best_model_name = results['Accuracy'].idxmax()

    print(f"\nMeilleur modèle: {best_model_name}")

    return X_train, X_test, y_train, y_test, results

# Application (exemple avec PRIX)
X_train, X_test, y_train, y_test, results = pipeline_data_mining(
    df_autos, target='PRIX', tache='regression'
)